name: win32_gui
description: Win32 API GUI in Object-Oriented style with some helpers. Uses package `win32` and `dart:ffi`.
version: 1.0.0
repository: https://github.com/gmpsddod/win32_gui

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.0.2
  win32: ^5.0.6
  logging: ^1.1.0
  resource_portable: ^3.1.0
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
