name: win32_gui
description: Win32 API GUI in Object-Oriented style with some helpers. Uses package `win32` and `dart:ffi`.
version: 1.1.4
repository: https://github.com/gmpassos/win32_gui
issue_tracker: https://github.com/gmpassos/win32_gui/issues

topics:
  - win32
  - windows
  - ffi

screenshots:
  - description: 'Example Screenshot'
    path: example/example-screenshot.png

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  win32: ^5.5.0
  logging: ^1.2.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.6
  dependency_validator: ^3.2.2
  coverage: ^1.6.3
