name: win32_gui
description: Win32 API GUI in Object-Oriented style with some helpers. Uses package `win32` and `dart:ffi`.
version: 1.2.0
repository: https://github.com/gmpassos/win32_gui
issue_tracker: https://github.com/gmpassos/win32_gui/issues

topics:
  - win32
  - windows
  - ffi

screenshots:
  - description: 'Example Screenshot'
    path: example/example-screenshot.png

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  ffi: ^2.1.4
  win32: ^5.12.0
  logging: ^1.3.0
  resource_portable: ^3.1.2
  collection: ^1.19.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  dependency_validator: ^5.0.2
  coverage: ^1.11.1
